"""empty message

Revision ID: 7f7b00859a37
Revises: 
Create Date: 2019-01-30 02:54:03.296703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7b00859a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('lang', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Word_associate',
    sa.Column('trans_to', sa.Integer(), nullable=False),
    sa.Column('trans_from', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trans_from'], ['word.id'], ),
    sa.ForeignKeyConstraint(['trans_to'], ['word.id'], ),
    sa.PrimaryKeyConstraint('trans_to', 'trans_from')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('translate_id', sa.Integer(), nullable=False),
    sa.Column('date_show', sa.DateTime(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['translate_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id', 'word_id', 'translate_id')
    )
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('dictionary_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('last_show', sa.DateTime(), nullable=True),
    sa.Column('show_count', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dict_id'], ['dictionary.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id', 'word_id', 'dict_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionary_word')
    op.drop_table('dictionary')
    op.drop_table('answer')
    op.drop_table('Word_associate')
    op.drop_table('word')
    op.drop_table('user')
    # ### end Alembic commands ###
