"""empty message

Revision ID: d954cb84d3c3
Revises: 6069134b485f
Create Date: 2019-01-27 21:05:34.661589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd954cb84d3c3'
down_revision = '6069134b485f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translate', sa.Column('trans_from', sa.Integer(), nullable=False))
    op.add_column('translate', sa.Column('trans_to', sa.Integer(), nullable=False))
    op.drop_constraint('translate_ibfk_1', 'translate', type_='foreignkey')
    op.drop_constraint('translate_ibfk_2', 'translate', type_='foreignkey')
    op.create_foreign_key(None, 'translate', 'word', ['trans_to'], ['id'])
    op.create_foreign_key(None, 'translate', 'word', ['trans_from'], ['id'])
    op.drop_column('translate', 'fir_word_id')
    op.drop_column('translate', 'sec_word_id')
    op.add_column('word', sa.Column('lang', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'lang')
    op.add_column('translate', sa.Column('sec_word_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('translate', sa.Column('fir_word_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'translate', type_='foreignkey')
    op.drop_constraint(None, 'translate', type_='foreignkey')
    op.create_foreign_key('translate_ibfk_2', 'translate', 'word', ['sec_word_id'], ['id'])
    op.create_foreign_key('translate_ibfk_1', 'translate', 'word', ['fir_word_id'], ['id'])
    op.drop_column('translate', 'trans_to')
    op.drop_column('translate', 'trans_from')
    # ### end Alembic commands ###
